#!/usr/bin/env python3
"""Write book/interactives.md: every interactive widget in the course, grouped
by module, read from the lessons' own iframes.

Each entry takes its name from the frame (or heading) that holds the iframe,
its description from the iframe's title attribute, and links to the widget on
its own and to the lesson. The page is generated, so a widget added to or
renamed in a lesson shows up here on the next run:

    python3 scripts/build_interactives.py
"""

from __future__ import annotations
import html
import re
from pathlib import Path

REPO = Path(__file__).resolve().parents[1]
BOOK = REPO / "book"

IFRAME = re.compile(r'<iframe\s+src="\.\./\.\./viz/([^"?#]+)[^"]*"(.*?)>', re.S)
TITLE_ATTR = re.compile(r'title="([^"]*)"')
FRAME = re.compile(r'^::::\{frame\}\s*(.*)$', re.M)
HEADING = re.compile(r'^#{2,3}\s+(.+)$', re.M)
H1 = re.compile(r'^#\s+(.+)$', re.M)

FEATURED = """\
## Four Cuts, Four Antennas

The same four pattern cuts, E-plane and H-plane in co-pol and cross-pol, on a
dipole, a small loop, a patch, and a horn. The antenna view shows what each cut
means; the chamber view shows how a turntable and a source horn take it. Lesson
9 uses the dipole; this is the full tool.

<iframe src="viz/pol-cuts.html"
        width="100%" height="538"
        style="border: 1px solid #cddce9; border-radius: 6px;"
        loading="lazy"
        title="A dipole, small loop, patch, or horn in 3-D with its pattern, the cut plane, and a probe horn: choose E-plane or H-plane and co-pol or cross-pol, or set the antenna's mount and the horn's polarization as on a chamber turntable">
</iframe>
"""


def module_captions() -> dict[int, str]:
    caps = {}
    for line in (BOOK / "_toc.yml").read_text().splitlines():
        m = re.match(r"\s*-\s*caption:\s*Module\s+(\d+)\s*[—-]\s*(.+)", line)
        if m:
            caps[int(m.group(1))] = m.group(2).strip()
    return caps


def lesson_label(page: Path, text: str) -> str:
    m = re.search(r"L(\d+)-", page.parent.name)
    if m:
        return f"L{int(m.group(1))}"
    h = H1.search(text)
    return h.group(1).strip() if h else page.parent.name


def entries():
    out = {}
    for page in sorted(BOOK.glob("module0*/*/index.md")):
        text = page.read_text()
        mod = int(page.parts[-3][-2:])
        for m in IFRAME.finditer(text):
            widget, attrs = m.group(1), m.group(2)
            t = TITLE_ATTR.search(attrs)
            desc = html.unescape(t.group(1)) if t else ""
            before = text[:m.start()]
            names = [(f.start(), f.group(1)) for f in FRAME.finditer(before)]
            names += [(h.start(), h.group(1)) for h in HEADING.finditer(before)]
            name = max(names)[1].strip() if names else widget
            rel = page.relative_to(BOOK).with_suffix(".html").as_posix()
            out.setdefault(mod, []).append((lesson_label(page, text), name, desc, widget, rel))
    return out


def main() -> None:
    caps = module_captions()
    lines = [
        "% Generated by scripts/build_interactives.py from the lessons' iframes.",
        "% Edit the lessons, not this page, and re-run the script.",
        "",
        "# Interactives",
        "",
        "Every interactive widget in the course, grouped by the module that",
        "introduces it. Open one on its own for the whole screen, or go to its",
        "lesson for the reasoning around it.",
        "",
        FEATURED,
    ]
    found = entries()
    for mod in sorted(found):
        lines.append(f"## Module {mod}: {caps.get(mod, '')}".rstrip(": "))
        lines.append("")
        for lesson, name, desc, widget, rel in found[mod]:
            item = f"- **{name}** ({lesson})"
            if desc:
                item += f". {desc[0].upper() + desc[1:]}"
                if not item.endswith("."):
                    item += "."
            item += (f' <a href="viz/{widget}" target="_blank" rel="noopener">Open</a>'
                     f' · <a href="{rel}">Lesson</a>')
            lines.append(item)
        lines.append("")
    (BOOK / "interactives.md").write_text("\n".join(lines))
    print(f"wrote book/interactives.md: {sum(len(v) for v in found.values())} widgets")


if __name__ == "__main__":
    main()
